"""update column sizes

Revision ID: 11058111dab5
Revises: b4d98362e0b8
Create Date: 2022-09-01 13:29:49.197279

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11058111dab5'
down_revision = 'b4d98362e0b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('target_user_profile', 'bio',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=400),
               existing_nullable=False)
    op.alter_column('target_user_profile', 'calendly_url',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('target_user_profile', 'email',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=200),
               existing_nullable=False)
    op.alter_column('target_user_profile', 'linkedin_url',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('target_user_profile', 'profile_image_url',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=250),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('target_user_profile', 'profile_image_url',
               existing_type=sa.String(length=250),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.alter_column('target_user_profile', 'linkedin_url',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    op.alter_column('target_user_profile', 'email',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.alter_column('target_user_profile', 'calendly_url',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.alter_column('target_user_profile', 'bio',
               existing_type=sa.String(length=400),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    # ### end Alembic commands ###
