"""add payment info columns to influencer tqable

Revision ID: 157fa5eb2a04
Revises: 30c2613a634a
Create Date: 2023-04-24 12:48:34.860652

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '157fa5eb2a04'
down_revision = '30c2613a634a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('influencer_profile', sa.Column('payment_method', sa.String(length=200), nullable=True))
    op.add_column('influencer_profile', sa.Column('payment_method_details', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('influencer_profile', 'payment_method_details')
    op.drop_column('influencer_profile', 'payment_method')
    # ### end Alembic commands ###
