"""create brand influencer channel map

Revision ID: 286422d1a945
Revises: 9c9e0dbac85d
Create Date: 2023-03-02 15:09:42.555939

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '286422d1a945'
down_revision = '9c9e0dbac85d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brand_influencer_channel_map',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_modified', sa.DateTime(), nullable=True),
    sa.Column('brand_email', sa.String(length=200), nullable=False),
    sa.Column('influencer_email', sa.String(length=200), nullable=False),
    sa.Column('channel_id', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('brand_influencer_channel_map')
    # ### end Alembic commands ###
