"""increase examples column length in contentpacks table

Revision ID: 4cc8402c6e0e
Revises: 6e48227dbe49
Create Date: 2023-04-11 12:52:33.745914

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4cc8402c6e0e'
down_revision = '6e48227dbe49'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('contentpacks', 'examples',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=10000),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('contentpacks', 'examples',
               existing_type=sa.String(length=10000),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    # ### end Alembic commands ###
