"""add delivery column to contentpacks table

Revision ID: 745e973e5ef4
Revises: 4cc8402c6e0e
Create Date: 2023-04-12 10:25:02.012075

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '745e973e5ef4'
down_revision = '4cc8402c6e0e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contentpacks', sa.Column('delivery', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contentpacks', 'delivery')
    # ### end Alembic commands ###
