"""add book_call_info to brand profile table

Revision ID: 7abbf388af8d
Revises: 286422d1a945
Create Date: 2023-03-16 16:01:07.880644

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7abbf388af8d'
down_revision = '286422d1a945'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('brand_user_profile', sa.Column('book_call_info', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('brand_user_profile', 'book_call_info')
    # ### end Alembic commands ###
