"""add portfolio url to influencers table

Revision ID: ae61248d1cf0
Revises: c2f5e3b61dde
Create Date: 2023-05-26 15:22:56.650978

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae61248d1cf0'
down_revision = 'c2f5e3b61dde'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('influencer_profile', sa.Column('portfolio_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('influencer_profile', 'portfolio_url')
    # ### end Alembic commands ###
