"""add columns for rate, and social urls

Revision ID: b3f87a58c74a
Revises: bce46b36530f
Create Date: 2022-11-29 15:05:43.134794

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3f87a58c74a'
down_revision = 'bce46b36530f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('target_user_profile', sa.Column('instagram_url', sa.String(length=255), nullable=True))
    op.add_column('target_user_profile', sa.Column('rate', sa.Integer(), nullable=True))
    op.add_column('target_user_profile', sa.Column('tiktok_url', sa.String(length=255), nullable=True))
    op.add_column('target_user_profile', sa.Column('website_url', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('target_user_profile', 'website_url')
    op.drop_column('target_user_profile', 'tiktok_url')
    op.drop_column('target_user_profile', 'rate')
    op.drop_column('target_user_profile', 'instagram_url')
    # ### end Alembic commands ###
