"""add submission_url to bookings table

Revision ID: b5892f55e6d7
Revises: e3da16ea6c09
Create Date: 2023-04-18 17:02:29.936588

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5892f55e6d7'
down_revision = 'e3da16ea6c09'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contentpack_bookings', sa.Column('submission_url', sa.String(length=20000), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contentpack_bookings', 'submission_url')
    # ### end Alembic commands ###
