"""add referrer column to user model

Revision ID: bce46b36530f
Revises: 42fa81089d7e
Create Date: 2022-09-26 12:38:07.627463

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bce46b36530f'
down_revision = '42fa81089d7e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('target_user_profile', sa.Column('referer', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('target_user_profile', 'referer')
    # ### end Alembic commands ###
