"""create campaign proposal table

Revision ID: c5f8e74eefa8
Revises: 95ad6599ebc3
Create Date: 2023-03-21 17:13:59.666690

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5f8e74eefa8'
down_revision = '95ad6599ebc3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('campaign_proposal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_modified', sa.DateTime(), nullable=True),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('influencer_email', sa.String(length=200), nullable=False),
    sa.Column('status', sa.String(length=100), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('campaign_proposal')
    # ### end Alembic commands ###
