"""brand user profile

Revision ID: d83e1e11b59a
Revises: b3f87a58c74a
Create Date: 2023-02-28 15:09:36.287434

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd83e1e11b59a'
down_revision = 'b3f87a58c74a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brand_user_profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_modified', sa.DateTime(), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('first_name', sa.String(length=200), nullable=True),
    sa.Column('last_name', sa.String(length=200), nullable=True),
    sa.Column('job_title', sa.String(length=200), nullable=True),
    sa.Column('company_name', sa.String(length=200), nullable=True),
    sa.Column('company_website', sa.String(length=200), nullable=True),
    sa.Column('company_description', sa.String(length=200), nullable=True),
    sa.Column('company_address', sa.String(length=200), nullable=True),
    sa.Column('company_email', sa.String(length=200), nullable=True),
    sa.Column('company_instagram', sa.String(length=200), nullable=True),
    sa.Column('company_linkedin', sa.String(length=200), nullable=True),
    sa.Column('company_logo', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('target_user_profile')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('target_user_profile',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('date_created', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('date_modified', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('linkedin_url', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('calendly_url', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('profile_image_url', sa.VARCHAR(length=250), autoincrement=False, nullable=False),
    sa.Column('city', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('country', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('bio', sa.VARCHAR(length=600), autoincrement=False, nullable=False),
    sa.Column('payment_info', sa.VARCHAR(length=600), autoincrement=False, nullable=True),
    sa.Column('referer', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('instagram_url', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('rate', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('tiktok_url', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('website_url', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='target_user_profile_pkey')
    )
    op.drop_table('brand_user_profile')
    # ### end Alembic commands ###
