"""create contentpack_bookinfs table

Revision ID: e3da16ea6c09
Revises: 745e973e5ef4
Create Date: 2023-04-14 15:17:30.527781

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3da16ea6c09'
down_revision = '745e973e5ef4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contentpack_bookings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_modified', sa.DateTime(), nullable=True),
    sa.Column('user_email', sa.String(), nullable=False),
    sa.Column('contentpack_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('details', sa.String(length=20000), nullable=True),
    sa.Column('copy', sa.String(length=20000), nullable=True),
    sa.Column('script', sa.String(length=20000), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('contentpack_bookings')
    # ### end Alembic commands ###
